# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.05.0306'

RELEASE_GIT_HEAD = '0763788ed3bd46a4935e2988b22591355fcf5fad'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'divStar/yt-dlp'

ORIGIN = 'divStar/yt-dlp'

_pkg_version = '2024.01.05.0306'
