# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.05.0440'

RELEASE_GIT_HEAD = '28e4eb24c040a400035dada81bb2361109e2aa3f'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'divStar/yt-dlp'

ORIGIN = 'divStar/yt-dlp'

_pkg_version = '2024.01.05.0440'
