# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.12.0216'

RELEASE_GIT_HEAD = 'e90283edac9b352352ca6756b354ed3c7ec32ab1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'divStar/yt-dlp'

ORIGIN = 'divStar/yt-dlp'

_pkg_version = '2024.01.12.0216'
